version: "3.3"

services:

  nginx:
    build: ./nginx
    env_file:
      - .env
    ports:
      - 80:80
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
